<h1 style="color:#2E86AB; font-family:Georgia; text-align:center; border-bottom: 3px solid #2E86AB; padding-bottom:10px;">
🏫 Predictor de Deserción Escolar en RD
</h1>

**Autor:** Eddy Luis  
**Fecha:** Abril 2026  
**Herramientas:** Python · Pandas · Scikit-learn · SHAP · Streamlit

---

## 📌 Descripción del Proyecto
Este proyecto analiza datos educativos públicos del Ministerio de Educación 
de la República Dominicana (MINERD) para predecir qué escuelas y perfiles 
de estudiantes tienen mayor riesgo de deserción escolar, y sugerir el tipo 
de intervención más adecuada para cada caso.

---

## 🎯 Objetivo
Construir un modelo predictivo que identifique centros educativos en riesgo 
y clasifique el tipo de intervención necesaria: apoyo económico, refuerzo 
académico, transporte o intervención familiar.

---

## 📁 Estructura del Proyecto

```text
📦 desercion_escolar_rd
│
├── 📂 data
│   ├── 📂 raw
│   │   └── 📄 Datos originales del MINERD
│   │
│   └── 📂 processed
│       └── 📄 Datos limpios y transformados
│
├── 📂 notebooks
│   ├── 📓 01_exploracion_datos.ipynb
│   ├── 📓 02_limpieza.ipynb
│   └── 📓 03_modelo.ipynb
│
├── 📂 src
│
├── 📂 outputs
│
└── 📄 requirements.txt
```

---

## 📋 Contenido de este Notebook

1. 📦 Importar Librerías
2. 📊 Cargar Dataset
3. 🧹 Limpieza de Datos
4. 📈 Análisis Exploratorio
5. 🤖 Entrenamiento del Modelo
6. 📉 Evaluación
7. ✅ Conclusiones

---

<h2 style="color:#A23B72; font-family:Georgia;">
📦 1. Importar Librerías
</h2>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Librerías cargadas")

Librerías cargadas

<h2 style="color:#A23B72; font-family:Georgia;">
📥 2. Cargar Datos
</h2>

In [2]:
df = pd.read_csv('../data/raw/centros_educativos_de_rd_2023_2024.csv', encoding='latin-1', sep=';', on_bad_lines='skip')
print(df.shape)
df.head()

(18350, 12)

,Regional,Distrito,Centros,Sector,Nivel,Coordenadas Latitud,Coordenadas Longitud,Matricula,Planta Fisica,Provincia,Municipio,Año
0,01 - BARAHONA,0101 - PEDERNALES,02334 - HERNANDO GORJON,PUBLICO,INICIAL - PRIMARIO - SECUNDARIO,18.032553,-71.746648,710,16000218 - HERNANDO GORJON,PEDERNALES,PEDERNALES,20222023
1,01 - BARAHONA,0101 - PEDERNALES,02335 - BIENVENIDO MORILLO,PUBLICO,INICIAL - PRIMARIO,18.045131,-71.743074,523,16000416 - BIENVENIDO MORILLO,PEDERNALES,PEDERNALES,20222023
2,01 - BARAHONA,0101 - PEDERNALES,02336 - EZEQUIEL HERNANDEZ MENDEZ,PUBLICO,INICIAL - PRIMARIO - SECUNDARIO,18.040663,-71.748256,652,16000812 - EZEQUIEL HERNANDEZ MENDEZ,PEDERNALES,PEDERNALES,20222023
3,01 - BARAHONA,0101 - PEDERNALES,02337 - EULALIO EMILIO MANCEBO REYES,PUBLICO,INICIAL - PRIMARIO,18.086838,-71.665969,76,16001015 - EULALIO EMILIO MANCEBO REYES,PEDERNALES,PEDERNALES,20222023
4,01 - BARAHONA,0101 - PEDERNALES,02338 - ARSENIO PEREZ PEÑA,PUBLICO,INICIAL - PRIMARIO,18.173358,-71.742050,60,16001119 - ARSENIO PEREZ PEÑA,PEDERNALES,PEDERNALES,20222023

In [3]:
print('Filas y columnas:', df.shape)

Filas y columnas: (18350, 12)

In [4]:
print(df.columns.tolist())

['Regional', 'Distrito', 'Centros', 'Sector', 'Nivel', 'Coordenadas Latitud', 'Coordenadas Longitud', 'Matricula', 'Planta Fisica', 'Provincia', 'Municipio', 'Año']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18350 entries, 0 to 18349
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Regional              18350 non-null  str
 1   Distrito              18350 non-null  str
 2   Centros               18350 non-null  str
 3   Sector                18350 non-null  str
 4   Nivel                 18350 non-null  str
 5   Coordenadas Latitud   18284 non-null  str
 6   Coordenadas Longitud  18131 non-null  str
 7   Matricula             18350 non-null  int64
 8   Planta Fisica         18350 non-null  str
 9   Provincia             18350 non-null  str
 10  Municipio             18350 non-null  str
 11  Año                   18350 non-null  int64
dtypes: int64(2), str(10)
memory usage: 4.5 MB

In [6]:
df.describe()

          Matricula           Año
count  18350.000000  1.835000e+04
mean     247.201689  2.022781e+07
std      258.548645  4.938663e+03
min        1.000000  2.022202e+07
25%       61.000000  2.022202e+07
50%      157.000000  2.023202e+07
75%      348.000000  2.023202e+07
max     2474.000000  2.023202e+07

In [7]:
df.isnull().sum()

Regional                  0
Distrito                  0
Centros                   0
Sector                    0
Nivel                     0
Coordenadas Latitud      66
Coordenadas Longitud    219
Matricula                 0
Planta Fisica             0
Provincia                 0
Municipio                 0
Año                       0
dtype: int64

In [8]:
df.head()

,Regional,Distrito,Centros,Sector,Nivel,Coordenadas Latitud,Coordenadas Longitud,Matricula,Planta Fisica,Provincia,Municipio,Año
0,01 - BARAHONA,0101 - PEDERNALES,02334 - HERNANDO GORJON,PUBLICO,INICIAL - PRIMARIO - SECUNDARIO,18.032553,-71.746648,710,16000218 - HERNANDO GORJON,PEDERNALES,PEDERNALES,20222023
1,01 - BARAHONA,0101 - PEDERNALES,02335 - BIENVENIDO MORILLO,PUBLICO,INICIAL - PRIMARIO,18.045131,-71.743074,523,16000416 - BIENVENIDO MORILLO,PEDERNALES,PEDERNALES,20222023
2,01 - BARAHONA,0101 - PEDERNALES,02336 - EZEQUIEL HERNANDEZ MENDEZ,PUBLICO,INICIAL - PRIMARIO - SECUNDARIO,18.040663,-71.748256,652,16000812 - EZEQUIEL HERNANDEZ MENDEZ,PEDERNALES,PEDERNALES,20222023
3,01 - BARAHONA,0101 - PEDERNALES,02337 - EULALIO EMILIO MANCEBO REYES,PUBLICO,INICIAL - PRIMARIO,18.086838,-71.665969,76,16001015 - EULALIO EMILIO MANCEBO REYES,PEDERNALES,PEDERNALES,20222023
4,01 - BARAHONA,0101 - PEDERNALES,02338 - ARSENIO PEREZ PEÑA,PUBLICO,INICIAL - PRIMARIO,18.173358,-71.742050,60,16001119 - ARSENIO PEREZ PEÑA,PEDERNALES,PEDERNALES,20222023